--11) Ingresar el siguiente Film.
/*Película: "The Good, the Bad and the Ugly"
Biografía: "Tres hombres violentos pelean por una caja que alberga 200 000 dólares, la cual fue escondida durante la Guerra Civil. 
Dado que ninguno puede encontrar la tumba donde está el botín sin la ayuda de los otros dos, deben colaborar, pese a odiarse."
Duración: 162 minutos
Fecha de Estreno: 11 de enero de 1968*/
/*INSERT INTO Peliculas VALUES('1968-01-11', 'The Good, the Bad and the Ugly', 162, 
'Tres hombres violentos pelean por una caja que alberga 200 000 dólares, la cual fue escondida durante la Guerra Civil. 
Dado que ninguno puede encontrar la tumba donde está el botín sin la ayuda de los otros dos, deben colaborar, pese a odiarse.', null)*/


